### ISSUE TITLE
Request... Custom commands

### ISSUE THREAD

**Issue by gjelsoe** [eclair4151/AlexaControlledSamsungTV#10]
Would it be possible make a custom command witch do a series of keypress
like "NetFlix" as hotword and being translated in my case into "SMART MENU",
"RIGHT BUTTON", "RIGHT BUTTON", "ENTER".

Michael

**Comment by eclair4151** [comment]
it looks like apps can be launched natively on the device for new TVS. Ill look into being able to launch apps on the TV.

https://github.com/Ape/samsungctl/issues/75

**Comment by eclair4151** [comment]
After more research this is not possible. Simply because the Alexa does not allow commands with the word Netflix in it :( 

Trying commands like 
launch/open Netflix on the TV
or 
change the channel to Netflix on the TV 

Causes Alexa to try to find a fire stick to launch apps on, even when there are none on your system. I have not found anyway to allow this app to respond to that command and launch its own apps. Closing for now until they update their SDK or someone finds a way to do this.

**Comment by gjelsoe** [comment]
The "hot word" could be anything now where Netflix isn't allowed :)
