### ISSUE TITLE
Run in cloud?

### ISSUE THREAD

**Issue by mattrabe** [eclair4151/AlexaControlledSamsungTV#8]
Hey there - got this running on a computer on my local network, works well with my MU6300 - it's great and I plan to add to its list of commands when I have time. Does this **have** to be running on the same local network as the TV, or is it possible to run it on a webserver? If running it on a webserver is not currently possible, do you think that enhancements to the code could enable or, or is there some blockage that will ever prevent that?

**Comment by eclair4151** [comment]
That tv will only accept commands over the local network. The only thing I can imagine that would work is in your router port forward 8001 to your TVs IP address and then in the web server in the tvconfig change the tv ip address field to your homes external IP address. 

This also means that turning your tv on won’t work because Wake On LAN doesn’t work over an external network (at least the way I have it set up. This could theoretically also be hacked together with port forwarding too but would take more code modification)

I have no clue if that this would actually work and have never tried. It also means you are leaving your tv access open to the world so anyone with your external IP can control your tv so use at your own risk. 

If you do get something working though let me know as I am curious if websockets would work over port forwarding
